### ISSUE TITLE
Come up with nomenclature for CSS variables, new values

### ISSUE THREAD

**Issue by cnasc** [with-backed/backed-interface#88]
Our current set of CSS variables:
```css
:root {
  --beige: #f4eae8;
  --black: #000000;
  --darkest-grey: #9e9e9e;
  --dark-grey: #dddddd;
  --light-grey: #eeeeee;
  --lightest-grey: #f7f7f7;
  --primary-blue: #0000ee;
  --primary-purple: #75187c;
  --secondary-purple: rgba(117, 24, 124, 0.2);
  --red: #d12424;
  --white: #ffffff;
  --yellow: #fffed1;
  --border-radius: 10px;
  --button-radius: 6px;
  --button-padding: 10px;
  /* We set this globally on html and body, may also need it in other places */
  --line-height: 1.6;
  --fieldset-padding: 24px;
  --serif: 'Times New Roman', Times, serif;
  --sans: Inter, Helvetica, sans-serif;
  --gap: 1.25rem;
}
```

Many of these have names that are too specific/not generic enough. Additionally, there may be some where we have variant values (text-small vs text-large?)

We should come up with more semantic names and apply the latest values from figma.
